#!/bin/bash
set -e                  # Stop after encountering an error.
shopt -s expand_aliases # Enable aliases.
alias voodoo='java -jar bootstrap-voodoo.jar'

voodoo pack sk copypack.lock.json
voodoo pack mmc copypack.lock.json
voodoo pack server copypack.lock.json
