#!/bin/bash
set -e                  # Stop after encountering an error.
shopt -s expand_aliases # Enable aliases.
alias voodoo='java -jar bootstrap-voodoo.jar'

voodoo flatten copypack.yaml -o copypack.json
voodoo build copypack.json -o copypack.lock.json --force
voodoo pack test mmc --clean copypack.lock.json
